# starship.toml

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$username\
[|](fg:#d8dee9)\
$directory\
[|](fg:#d8dee9)\
$git_branch\
[ ](fg:#d8dee9)\
"""

# Single-line prompt
[line_break]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
show_always = true
style_user = "fg:#b48ead"
style_root = "fg:#b48ead"
format = '[$user ]($style)'
disabled = false

[directory]
style = "fg:#8fbcbb"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:#ebcb8b"
format = '[ $symbol $branch ]($style)'
