format = """
$username\
[|](fg:#d8dee9)\
$directory\
[|](fg:#d8dee9)\
$git_branch\
[ ](fg:#d8dee9)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

[username]
show_always = true
style_user = "fg:#b48ead"
style_root = "fg:#b48ead"
format = '[$user ]($style)'
disabled = false

[directory]
style = "fg:#8fbcbb"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:#ebcb8b"
format = '[ $symbol $branch ]($style)'