format = """
[](#4f4f4f)\
$username\
[](bg:#d86365 fg:#4f4f4f)\
$directory\
[](fg:#d86365 bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$docker_context\
[ ](fg:#86BBD8)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

[username]
show_always = true
style_user = "bg:#4f4f4f"
style_root = "bg:#4f4f4f"
format = '[$user ]($style)'
disabled = false

[directory]
style = "bg:#d86365"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'
